name: Generate iCal

on:
  push:
    paths:
      - 'src/schedule.json'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: チェックアウトリポジトリ
      uses: actions/checkout@v2

    - name: Node.jsのセットアップ
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: 依存関係のインストール
      run: npm install

    - name: JSONを読み込んでiCalを生成
      run: npx tsc && node dist/generate_ical.js

    - name: Gitの設定
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

    - name: iCalをコミット
      run: |
        if [ -f dist/schedule.ics ]; then
          git add dist/schedule.ics
          git commit -m "Update schedule.ics"
          git push https://${{ secrets.GH_TOKEN }}@github.com/johndoe/Json2iCal.git HEAD:main
        else
          echo "dist/schedule.ics not found"
