name: Generate iCal

on:
  push:
    paths:
      - 'src/schedule.json'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: チェックアウトリポジトリ
      uses: actions/checkout@v2

    - name: Node.jsのセットアップ
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: 依存関係のインストール
      run: npm install

    - name: JSONを読み込んでiCalを生成
      run: npx tsc && node dist/generate_ical.js

    - name: iCalをコミット
      run: git add calendar.ics && git commit -m "Update calendar.ics" && git push